# -*- coding: utf-8 -*-
"""6(5)_Technicians_should_be_able_to_start_&_stop_the_answering_process.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1267kXwKOh1apSH3fBfjxW2tOW4iCtYet

This task will be mostly held with the Realware Device in built commands and its 4 microphones
"""

