# -*- coding: utf-8 -*-
"""8(2)_Convert_the_Word_template_into_text_in_the_Mongo_database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w8NmqidbA4FNCjSGrg3M0mzaW1B8OEte
"""

