[auth]
redirect_uri="http://localhost:8501/oauth2callback"
cookie_secret="b7f8e5cf91f748d3b61436c54df93412b5c928f1a8b340c1a9de00b6a07f3f34"

[auth.google]
client_ID="729770667815-5svureisfbu0p4915luh5inst50m90mg.apps.googleusercontent.com"
client_secret="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"
server_metadata_url="htpps://accounts.google.com/.well-known/openid-configuration"
