# -*- coding: utf-8 -*-
"""11(11)_Signatures_not_required._RFO_Services_will_create_the_electronic_signature.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RlS2TY1z60T1pdjxSDbnzlRkPbp34ED
"""

from docx import Document
from docx.shared import Inches
import datetime

def add_technician_signature_image(doc, signature_image_path):
    """
    Add an image of the technician's signature to the document.
    :param doc: The Document object.
    :param signature_image_path: Path to the signature image file (e.g., PNG, JPEG).
    """
    # Add a section for the signature at the end of the document
    doc.add_paragraph("\n")
    doc.add_paragraph("Signature: ")

    # Insert the signature image
    doc.add_picture(signature_image_path, width=Inches(2))  # Adjust the width as needed
    doc.add_paragraph(f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    doc.save("Questionnaire_with_Signature.docx")
    print(f"Document saved with the technician's signature image.")

# Example usage
signature_image_path = "signature.png"  # Path to the stored signature image file
doc = Document('Questionnaire_Results.docx')  # Load the previously created document
add_technician_signature_image(doc, signature_image_path)

import datetime

# Function to create the report with an electronic signature (if required)
def generate_report_with_signature(report_data):
    try:
        # Create an electronic signature (dummy example for now)
        electronic_signature = "RFO Services Generated Signature"

        # Combine report data with the electronic signature
        report_entry = {
            "report_data": report_data,
            "electronic_signature": electronic_signature,
            "created_at": datetime.datetime.now()
        }

        # Save to MongoDB
        collection.insert_one(report_entry)
        print("Report with electronic signature saved to MongoDB collection 'Reports'.")
    except Exception as e:
        print(f"Error saving report to MongoDB: {e}")

# Example of using the function to save a report with an electronic signature
report_data = {"status": "success", "message": "RFO Services will create the electronic signature."}
generate_report_with_signature(report_data)
