name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the CI/CD on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Define the type of runner to use

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the code from your GitHub repo

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        version: latest  # Set the Docker Buildx version

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # DockerHub username
        password: ${{ secrets.DOCKER_PASSWORD }}  # DockerHub password

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .  # Build the Docker image
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}  # Push the image to DockerHub (or another registry)

    - name: Set up Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh  # Install Railway CLI
        railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}  # Login using Railway API key

    - name: Deploy to Railway
      run: |
        railway up --projectId ${{ secrets.RAILWAY_PROJECT_ID }}  # Deploy to Railway
