name: Deploy to Railway

on:
  push:
    branches:
      - main  # Trigger deployment on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v3

      - name: ⚙️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔐 Login to Railway Container Registry
        run: echo "${{ secrets.RAILWAY_API_TOKEN }}" | docker login --username $RAILWAY_USER --password-stdin registry.gcp.railway.app
        env:
          RAILWAY_USER: ${{ secrets.RAILWAY_PROJECT_ID }}

      - name: 📦 Build and Push Docker Image to Railway
        run: |
          docker build -t registry.gcp.railway.app/${{ secrets.RAILWAY_PROJECT_ID }}/my-fastapi-app .
          docker push registry.gcp.railway.app/${{ secrets.RAILWAY_PROJECT_ID }}/my-fastapi-app

      - name: 🚀 Trigger Railway Deployment
        run: curl -X POST "https://backboard.railway.app/project/${{ secrets.RAILWAY_PROJECT_ID }}/deploy?service=${{ secrets.RAILWAY_SERVICE_ID }}" \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}"
