name: Deploy to Heroku

on:
  push:
    branches:
      - main  # You can adjust this to your preferred branch (e.g., `master`)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # You can change this version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Heroku deploy
      uses: akshnz/heroku-deploy@v2.2.0
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
        heroku_email: ing.juan.rivera2@gmail.com  # Replace with your Heroku email