name: Execute Notebook Workflow

on:
  push:
    branches: [main]

jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nbconvert nbclient

    - name: Execute Workflow Steps
      run: |
        echo "🔁 Executing notebooks in workflow order..."
        for nb in $(find . -name "*.ipynb" | grep -o "[^/]*([0-9]\+)_.*\.ipynb" | sort -t '(' -k2n); do
          echo "📘 Running: $nb"
          jupyter nbconvert --to notebook --execute "$nb" --inplace
        done

    - name: Commit Executed Notebooks (Optional)
      if: success()
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add *.ipynb
        git commit -m "🤖 Executed notebooks via GitHub Actions"
        git push
      continue-on-error: true
